<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="image\icons\**" />
    <EmbeddedResource Remove="image\icons\**" />
    <None Remove="image\icons\**" />
    <Page Remove="image\icons\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="image\city.png" />
    <None Remove="image\country.png" />
    <None Remove="image\details.png" />
    <None Remove="image\expreience.png" />
    <None Remove="image\favourite.png" />
    <None Remove="image\history.png" />
    <None Remove="image\szallas.png" />
    <None Remove="image\user.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="image\city.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="image\country.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="image\details.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="image\expreience.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="image\favourite.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="image\history.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="image\szallas.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="image\user.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
